### ISSUE TITLE
a suggest, Supfile default filename should be Supfile.yml

### ISSUE THREAD

**Issue by andares** [pressly/sup#100]
Like .styleci.yml, appveyor.yml, composer.json, etc. It can be support by editor.

**Comment by eduardonunesp** [comment]
At least support `Supfile.yaml` or `Supfile.yml`as alternatives can be a good idea, I can prepare a PR for that

**Comment by VojtechVitek** [comment]
Supfile > Supfile.yml > `sup -f CustomSupfile`

**Comment by VojtechVitek** [comment]
We picked Supfile based on Makefile and Dockerfile. But I understand where this is coming from: YML IDE formatting doesn't work right away, am I right? :)

**Comment by VojtechVitek** [comment]
Given the number of thumb ups, expect a PR in couple minutes.

**Comment by VojtechVitek** [comment]
Implemented. Thanks for this suggestion!
