### ISSUE TITLE
Running Sup from Supfile

### ISSUE THREAD

**Issue by tpaz** [pressly/sup#102]
Sup version: 0.5 (pulled today)

Following the README documentation, I tried to use sup within Supfile.
Either there is a bug or the documentation is misleading.
Instead of instantiating a sub-process as the README says on the machine where sup is executed, it actually tries to run the sup tool on the Remote machine where sup (parent) is supposed to execute the "run" command.

example:
[results@control experiment]$ sup worker1 cloud_suite_bench
root@worker1:22 | bash: sup: command not found
root@worker1:22 | Process exited with status 127

Supfile code:
cloud_suite_bench:
        desc: install && run cloud_suite benchmark (based on ENV vars)
        run: >
            sup -f ./cloudsuite/Supfile $SUP_ENV $SUP_NETWORK run_bench

The "sub" sup file is in ./cloudsuite folder as hinted above, here is its content just for reference:

commands:
    run_benchmark:
        desc: install and run cloud_suite benchmark. Prerequisites - Docker + Compose + swarm cluster configured on 3 worker nodes.
        upload:
          - src: ./docker-compose.yml
            dst: /root/
        run: >
            docker-compose up -d --build --project-name cloudsuite --force-recreate $CLOUD_BENCH
            && docker run --rm --net spark-net --volumes-from movielens-dataset cloudsuite/in-memory-analytics /data/ml-latest-small /data/myratings.csv --master spark://spark-master:7077
            # TODO: collect results
    cleansing:
        desc: clean all leftovers after bench over. just to make sure...
        run: >
            docker-compose down
targets:
    run_bench:
     - run_benchmark
     - cleansing

I suppose it has nothing to do with the 'sub' sup file, rather the fact that the "run:" command is expected to execute its arguments on the remote worker machine rather on the control machine where it was initiated. This is in contrast to the expected behavior based on the README description.

Ideas?
TIA

**Comment by tpaz** [comment]
I replaced "run:" with "local:" command and it seems to work now.

So bug is on README. need to fix the above in "Running Sup from Supfile" section.

**Comment by VojtechVitek** [comment]
This seems to be fixed for a while..

**Comment by Mingan** [comment]
It's not fixed on the website.

**Comment by VojtechVitek** [comment]
https://github.com/pressly/sup/tree/gh-pages branch
