### ISSUE TITLE
Sup would not be updated

### ISSUE THREAD

**Issue by mingrammer** [pressly/sup#116]
If I run `sup`, the console shows this message:

```
unsupported version 1.0

Please update sup by `go get -u github.com/pressly/sup/cmd/sup`
```

But, that command does not update the sup.

Any solutions?

**Comment by VojtechVitek** [comment]
Seems like your Supfile version is old, not the client. The message is confusing, sorry about that. Mind opening PR?

**Comment by mingrammer** [comment]
@VojtechVitek I got it, Yes, I'm willing to fix this by PR :)

**Comment by mingrammer** [comment]
Assign this issue to me please
