### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by hauleth** [pressly/sup#118]
It seems like nice project, however I see it is a little bit rotting right now.

**Comment by pkieltyka** [comment]
@hauleth the project is very stable and in use by many people. We support many OSS projects, and have other jobs etc. If you want something done, submit a PR or help with reviews.

**Comment by VojtechVitek** [comment]
Yeah, this project is still very alive and used every day!

The codebase needs some more love from the community, though. I'm doing my best to address important bugs asap, all in my spare time. Any additional features need to wait until there's time to address them.

**Comment by pkieltyka** [comment]
Send some ETH or PRs :)

**Comment by hauleth** [comment]
Woah, hold your horses. I asked in good faith as I see great potential in it and it seemed like a little stagnation (no new versions for over a year, 0.6 as the lasted released version, a lot of old issues and  PRs and I was concerned as I really like the project and I would like it to grow, however I am not Gopher myself. And for me some of the PRs are must have, like #105 or #87 and are blocking me from using this project.

**Comment by VojtechVitek** [comment]
FYI. I found some spare time and I'm merging new PRs - whatever is ready.

Sup's Not Dead! 😆
