### ISSUE TITLE
Get remote execution command status

### ISSUE THREAD

**Issue by kashp** [pressly/sup#155]
How can we get the exit status of remote command along with stdout and stderr.

**Comment by VojtechVitek** [comment]
You can print the status in the bash command

```
echo "success"
echo $?
```

The sup is only concerned about the status of the full terminal session. Any non-zero status will be shown as an error.

A good practice is to enable strict mode, where the terminal exits on any error:
```
set -e
```

Does this help?

**Comment by kashp** [comment]
Thanks for the reply, That make sense i will try to parse logs in sup.
