### ISSUE TITLE
Feature Request: Add kubernetes pod connection type

### ISSUE THREAD

**Issue by stephencheng** [pressly/sup#160]
Give that I have a KUBECONFIG with all certs and cluster info configured
I want that I am able to run sup command(shelll command etc) in side the kubernetes pod instead of ssh connection by default

This is similar to ansible connection plugin, such as docker/kubectrl: https://docs.ansible.com/ansible/latest/plugins/connection.html#using-connection-plugins

Essentially, the connection will be established via command:  kubectl exec -it pod_name /bin/bash

Is this possible?

**Comment by VojtechVitek** [comment]
This is not possible. Sup was designed to work over SSH only. And I don't intend to change that.

I'd not combine Sup with Kubernetes; unless you want to SSH into the kubelet nodes.
