### ISSUE TITLE
I installed Golang. But your installation doesn't seem to be working. 

### ISSUE THREAD

**Issue by pitosalas** [pressly/sup#172]
I am using Fish shell, but I don't think that matters. I did `brew install go`. I also used the dmg in experimenting. I updated the $PATH. I can `go version` and that works. `go list` gives an obscure message:
```
can't load package: package .: no Go files in /Users/pitosalas/mydev/soa_demo
```
But I continued and did: `go get -u github.com/pressly/sup/cmd/sup` which completed without error.

And yet I don't have a sup command. I can't tell because I don't program in Go where the problem lies. Thanks.

**Comment by VojtechVitek** [comment]
If you're new to Go, you might want to prefer downloading sup from
https://github.com/pressly/sup/releases

**Comment by pitosalas** [comment]
Thanks. How do I install that file? Where do I put it? It's not a format that I recognize.

Pito Salas
Brandeis Computer Science
Volen 134

**Comment by VojtechVitek** [comment]
sup-darwin64
sup-linux386
sup-linux64
sup-windows386.exe
sup-windows64.exe

all of them are executables built for different platforms/architecture
