### ISSUE TITLE
Does sup support ansible's ranges of hosts?

### ISSUE THREAD

**Issue by cocotyty** [pressly/sup#178]
make be like:
[https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#adding-ranges-of-hosts](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#adding-ranges-of-hosts)

**Comment by VojtechVitek** [comment]
See https://github.com/pressly/sup#network `inventory`. You can do something like

```
inventory: |
  for i in $(seq 1 100); do echo www.$i.example.com; done
```
