### ISSUE TITLE
Add this project to Awesome-Go

### ISSUE THREAD

**Issue by eduardonunesp** [pressly/sup#19]
https://github.com/avelino/awesome-go :-)

**Comment by VojtechVitek** [comment]
@eduardonunesp we'd be glad if anyone created that PR :)

**Comment by eduardonunesp** [comment]
Cool ! I can do that :+1:

**Comment by eduardonunesp** [comment]
Added to Awesome-Go https://github.com/avelino/awesome-go#other-software

**Comment by pkieltyka** [comment]
thanks :)
