### ISSUE TITLE
Add serial command, like ansible

### ISSUE THREAD

**Issue by pkieltyka** [pressly/sup#5]
This runs only on N number of servers at a time..

**Comment by VojtechVitek** [comment]
We can have Supfile `command` field:
- `max: 2`

And/or
- `sup --max=2` cmd option.

**Comment by pkieltyka** [comment]
I kind of like the word "serial", because it indicates the dependency as serial instead of parallel... ie --serial=2  or serial: 2

**Comment by VojtechVitek** [comment]
Yea, I already have WIP for `serial`.

**Comment by lexa-uw** [comment]
:+1:
