### ISSUE TITLE
CLI to accept multiple commands

### ISSUE THREAD

**Issue by pkieltyka** [pressly/sup#7]
ie. `sup beta pull build ps`

**Comment by eduardonunesp** [comment]
:+1:

**Comment by lexa-uw** [comment]
Why you do not want use ```targets``` option in config file?

**Comment by VojtechVitek** [comment]
@lexa-uw sup description:
> think of it like 'make' for a network of servers

`make` also accepts multiple commands/targets.

Yes, the same thing can be achieved with "targets" -- but this is just a convenient sugar that doesn't add any more complexity.

**Comment by eduardonunesp** [comment]
Yeah, but would be cool a command like `sup stg --target cmd1 cmd2 cmd3`, it's just instant target, maybe is simple to implement

**Comment by VojtechVitek** [comment]
@eduardonunesp it's already implemented in master, you can try running multiple commands/targets using `sup <network> cmd1 cmd2 target cmd6`

**Comment by eduardonunesp** [comment]
Oh sorry, thanks
