### ISSUE TITLE
Is it possible to display only the command(s) output when running a sup command ?

### ISSUE THREAD

**Issue by AmitKumarDas** [pressly/sup#81]
1/ My Supfile snippet:
```
  hello:
    desc: Greeting that understand dynamic inputs
    run: echo "HI ${SOMEONE}"
```

2/ Can we have only the output of the command ? 
Is there any option to hide the verboseness in the output ?
In this case I just want **HI amit** & nothing else.
```
[root@localhost home]# sup -e SOMEONE=amit -f /etc/openebs/Supfile local hello
root@localhost | + echo 'HI amit'
root@localhost | HI amit
```

**Comment by VojtechVitek** [comment]
@AmitKumarDas not right now, but I guess we could implement it. You'd get server prefix on each line, though.

```
[root@localhost home]# sup -e SOMEONE=amit -f /etc/openebs/Supfile local hello
root@localhost | HI amit
```

**Comment by AmitKumarDas** [comment]
Thanks @VojtechVitek for being so responsive.

I tested it out & it works as expected.

# sup -f /etc/openebs/test.conf -e SOMEONE=DAS local hello
root@localhost | HI DAS

My intention was to display pretty formatted output as-is.
I will use below for the time being.
```
sup -f /etc/openebs/test.conf -e SOMEONE=DAS local hello | cut -f 3- -d ' '
HI DAS
```

**Comment by VojtechVitek** [comment]
Cheers 👍
