### ISSUE TITLE
Bug running `w` remote command

### ISSUE THREAD

**Issue by pkieltyka** [pressly/sup#88]
[peter@pak ~/Dev/go/src/github.com/pressly/imgry]$ sup production w
ubuntu@imgry1.x.pressly.io:22 | w: 40 column window is too narrow
ubuntu@imgry3.x.pressly.io:22 | w: 40 column window is too narrow
ubuntu@imgry2.x.pressly.io:22 | w: 40 column window is too narrow
ubuntu@imgry2.x.pressly.io:22 | Process exited with status 1
ubuntu@imgry1.x.pressly.io:22 | Process exited with status 1

**Comment by VojtechVitek** [comment]
Most probably upstream bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=183394

We might introduce an option to disable TTY for a certain command, which would "fix" these types of bugs.

**Comment by VojtechVitek** [comment]
A workaround is running `w|cat`, where cat hides the underlying TTY's stdout fd with its raw stdin fd.
