### ISSUE TITLE
Installation failing on Ubuntu 14.04 machine

### ISSUE THREAD

**Issue by lym** [pressly/sup#91]
When I try to install following the instructions on the [project page](https://pressly.github.io/sup/), the installation fails with:

    # github.com/pressly/sup/vendor/golang.org/x/crypto/curve25519
    go/src/github.com/pressly/sup/vendor/golang.org/x/crypto/curve25519/doc.go:15: undefined: scalarMult

My go version is 1.6.2

**Comment by VojtechVitek** [comment]
@lym what's your architecture?

can you run
`go verison` and
`go env`

**Comment by VojtechVitek** [comment]
I guess we should rather report this against https://github.com/golang/crypto

**Comment by lym** [comment]
~$ go version
     go version go1.6.2 linux/386

    ~$ go env
    GOARCH="386"
    GOBIN=""
    GOEXE=""
    GOHOSTARCH="386"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH="/home/lym/go"
    GORACE=""
    GOROOT="/opt/go"
    GOTOOLDIR="/opt/go/pkg/tool/linux_386"
    GO15VENDOREXPERIMENT="1"
    CC="gcc"
    GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0"
    CXX="g++"
    CGO_ENABLED="1"

**Comment by VojtechVitek** [comment]
Thanks, I'll try to build binaries for Linux 386. Let's see

**Comment by VojtechVitek** [comment]
Ok, I figured it out. Bug in vendoring tool that we use. I'll push fix and new release in a bit.

**Comment by VojtechVitek** [comment]
Fixed in https://github.com/pressly/sup/commit/22479dfbdaa11f80c790b05acd76349a66cc46c7. Released v0.4.2.

@lym Can you please confirm it works for you?

**Comment by lym** [comment]
Yes it does :-) Thank you!
