### ISSUE TITLE
ver 0.4 - "script" command exception

### ISSUE THREAD

**Issue by tpaz** [pressly/sup#93]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x4b81e0]

goroutine 45 [running]:
panic(0x6fd580, 0xc82000e130)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/pressly/sup.(*SSHClient).WriteClose(0xc8200d4000, 0x0, 0x0)
	/home/user/dev/go/src/github.com/pressly/sup/ssh.go:273 +0x40
github.com/pressly/sup.(*Stackup).Run.func4(0xc8200f0530, 0x1, 0x1, 0xc82002c040, 0xc8200e88c0)
	/home/user/dev/go/src/github.com/pressly/sup/sup.go:180 +0x19b
created by github.com/pressly/sup.(*Stackup).Run
	/home/user/dev/go/src/github.com/pressly/sup/sup.go:182 +0x11cf

Sup file related section:
run_some_script:
        desc: bla bla
        upload:
            - src: ./run_script.sh
              dst: /opt/dest/
        script: ./run_script.sh

when using run command with upload the script runs...

**Comment by VojtechVitek** [comment]
I'll take a look later this week, feel free to remind me.

In the meantime, can you try removing "upload", since you're using `script` directly?

**Comment by tpaz** [comment]
sure
